### ISSUE TITLE
Commands not appearing in Discord

### ISSUE THREAD

**Issue by eqagunn** [airman604/discord-zerotier-bot#1]
```
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: ["gateway-prd-main-t7ln",{"micros":74525,"calls":["discord-sessions-blue-prd-2-156",{"micros":73636,"calls":["start_session",{"micros":24761,"calls":["api-prd-main-289j",{"micros":22026,"calls":["get_user",{"micros":2278},"add_authorized_ip",{"micros":1173},"get_guilds",{"micros":3218},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 5989559af0206882e3db2ff91b9d88d5).
INFO:discord_slash:Syncing commands...
INFO:root:Ready!
INFO:discord_slash:Syncing permissions...
INFO:discord_slash:Completed syncing all commands!
```

Script seems to execute fine, the bot is online, but no commands present in Discord hours after. Any idea?
EDIT: Forgot to mention; I'm running the bot directly, outside Docker, on Windows.

**Comment by airman604** [comment]
Hey @eqagunn hours sound like too much. Are you still having issues? I'm assuming you did all the configuration (steps 1-3)?

Windows shouldn't matter I think, though I haven't tested. As you're not using Docker, how are you passing the tokens to the script (i.e. `DISCORD_TOKEN`, `ZT_NETWORK`, `ZT_TOKEN` - from template.env)?

**Comment by eqagunn** [comment]
Hi. Issue still present. I have modified the bot a tiny bit:
- Renamed _template.env_ to _config.py_ and moved it to _src_ folder.
- In _config.py_ lowercased the variables and enclosed values in apostrophes.
- Added line `from config import *` to _bot.py_.
- Removed `zt_token = os.getenv("ZT_TOKEN")`, `zt_network = os.getenv("ZT_NETWORK")` and `discord_token = os.getenv("DISCORD_TOKEN")` from _bot.py_.

**Comment by airman604** [comment]
I see, so that's weird. Can you try changing the logging level in the first line in `main()` from:

```python
    logging.basicConfig(level=logging.INFO)
```

to

```python
    logging.basicConfig(level=logging.DEBUG)
```

and provide the output of the script when you run it.

**Comment by eqagunn** [comment]
Here you go: https://pastebin.com/RhBe9rSH

**Comment by airman604** [comment]
Looked at the logs, I can't see anything wrong going on with the script. Let me do a bit of testing, have to refresh my memory how it all works and whether there's any configuration gotchas I might've missed in the readme.

**Comment by eqagunn** [comment]
Any luck?

**Comment by airman604** [comment]
Can't reproduce

**Comment by airman604** [comment]
Can't reproduce
