### ISSUE TITLE
SEND HELP!

### ISSUE THREAD

**Issue by epokuser** [airman604/discord-zerotier-bot#2]
THIS IS URGENT!, PLEASE HELP!
i dont know how to make the bot work without docker on windows!
so please help! 
and the import discord_slash doesn't work :(
as pip install discord_slash module is missing!

**Comment by airman604** [comment]
What environment are you trying to run the bot in?
Have you tried running `pip install -r requirements.txt` in the **src** directory?

**Comment by GitPhane** [comment]
I had the same problem, however when I typed $help this happened
![image](https://user-images.githubusercontent.com/107200256/176253591-cea93c43-fead-425f-9211-9681d544c43e.png)
Slash commands arent working

**Comment by airman604** [comment]
I don't have any Windows boxes around (or free time for that matter) to troubleshoot this. I'd suggest to install Docker Desktop and then follow REAMDE.
