### ISSUE TITLE
When I run the bot,on ssh I cant use the ssh

### ISSUE THREAD

**Issue by epokuser** [airman604/discord-zerotier-bot#3]

**Comment by epokuser** [comment]
![image](https://user-images.githubusercontent.com/81563688/226589500-e9262dd9-e1a3-4b00-a3cb-dc65cd9db530.png)


I mean I can use ctrl+c to quit the bot which makes the bot stop working
I want the bot to run and I can do other things in the ssh window

**Comment by airman604** [comment]
If you're following the README and running it as a Docker container, replace `-it` with `-d` to run it in the background:

```
docker run --rm -d --env-file .env discord-zerotier-bot
```
